---
name: Build Container Image

# What it does: Build container image & push it to GHCR (except for PRs)
# Why it exists: Automated publishing

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request: {}

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: mhutter/yamllint

jobs:
  # Push image to GitHub Packages.
  container:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Log in to the Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine Tags & Labels based on Git ref
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}"

      - name: Build & Push container image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
